GET http://localhost:3000

###Get links
GET http://localhost:3000/?url=https://en.wikipedia.org/wiki/Main_Page&option=links

###Get screenshots
GET http://localhost:3000/?url=https://en.wikipedia.org/wiki/Main_Page&option=screenshot
